# Generated by Django 4.2.7 on 2025-11-23 02:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_between_calls', models.IntegerField(default=5, help_text='Seconds between each number call')),
                ('card_selection_timer', models.IntegerField(default=30, help_text='Seconds for card selection window')),
                ('bid_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Default bet amount per card', max_digits=10)),
                ('percentage_cut', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage to cut from total derash (e.g., 10.00 for 10%)', max_digits=5)),
                ('min_withdraw', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum withdrawal amount', max_digits=10)),
                ('total_cards', models.IntegerField(default=90, help_text='Total number of cards available')),
                ('deposit_accounts', models.JSONField(default=dict, help_text="Bank account details: {'BOA': {'name': '...', 'number': '...'}, 'CBE': {...}, 'Telebirr': {...}}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Settings',
                'verbose_name_plural': 'Game Settings',
                'db_table': 'game_settings',
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('platform', models.CharField(choices=[('BOA', 'Bank of Abyssinia'), ('CBE', 'Commercial Bank of Ethiopia'), ('Telebirr', 'Telebirr')], max_length=20)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdraw_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='withdraw_re_status_586958_idx'), models.Index(fields=['user', 'status'], name='withdraw_re_user_id_ae4545_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('platform', models.CharField(choices=[('BOA', 'Bank of Abyssinia'), ('CBE', 'Commercial Bank of Ethiopia'), ('Telebirr', 'Telebirr')], max_length=20)),
                ('deposit_text', models.TextField(help_text='Text or screenshot description from user')),
                ('photo_file_id', models.CharField(blank=True, help_text='Telegram file_id for screenshot', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deposit_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='deposit_req_status_d9c8cf_idx'), models.Index(fields=['user', 'status'], name='deposit_req_user_id_aedeb5_idx')],
            },
        ),
    ]
