# Generated by Django 4.2.7 on 2025-11-24 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gamesettings_withdrawrequest_depositrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, help_text='All winners (for split derash)', related_name='shared_wins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when bingo was claimed', null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='mode_history',
            field=models.JSONField(default=list, help_text="List of mode changes: [{'mode': 'automatic', 'timestamp': '...'}, ...]"),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='automatic_mode_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, automatic mode will be available for all players'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('show_refund', models.BooleanField(default=False)),
                ('show_cancel', models.BooleanField(default=False)),
                ('refund_processed', models.BooleanField(default=False)),
                ('cancel_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='api.game')),
            ],
            options={
                'db_table': 'admin_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.transfer'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_user', 'created_at'], name='transfers_from_us_08d98d_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_user', 'created_at'], name='transfers_to_user_ce71c0_idx'),
        ),
    ]
