# Generated by Django 4.2.7 on 2025-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_winners_gamecard_claimed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'second_admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='time_between_calls',
            field=models.IntegerField(default=3, help_text='Seconds between each number call'),
        ),
    ]
