# Generated by Django 4.2.7 on 2025-12-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_secondadmin_alter_gamesettings_time_between_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='support_phone',
            field=models.CharField(default='0952838412', help_text='Support phone number displayed in bot support command', max_length=20),
        ),
    ]
