# Generated by Django 4.2.7 on 2025-12-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fakeuser_gamesettings_allow_system_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='system_accounts_max',
            field=models.IntegerField(default=30, help_text='Maximum number of system accounts to join each game'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='system_accounts_min',
            field=models.IntegerField(default=15, help_text='Minimum number of system accounts to join each game'),
        ),
    ]
