# Generated by Django 4.2.7 on 2025-12-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gamesettings_system_accounts_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='winning_patterns',
            field=models.JSONField(default=list, help_text="List of enabled winning patterns: ['horizontal', 'vertical', 'diagonal', 'corner', 'full_card']"),
        ),
    ]
