# Generated by Django 4.2.7 on 2026-07-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_secondadmin_password_plain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedLotteryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_purchase_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('reject', 'Rejected'), ('delete', 'Deleted')], db_index=True, max_length=20)),
                ('prior_status', models.CharField(blank=True, default='', max_length=20)),
                ('full_name', models.CharField(blank=True, default='', max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('numbers', models.JSONField(blank=True, default=list)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_holder', models.CharField(blank=True, default='', max_length=160)),
                ('bank_account', models.CharField(blank=True, default='', max_length=64)),
                ('paid_from_account', models.CharField(blank=True, default='', max_length=64)),
                ('receipt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('admin_note', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
                ('removed_by', models.CharField(blank=True, default='admin-view', max_length=120)),
                ('removed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'lottery_deleted_receipts',
                'ordering': ['-removed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedLotteryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('preferred_language', models.CharField(blank=True, default='', max_length=5)),
                ('is_guest', models.BooleanField(default=False)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('verified_numbers', models.JSONField(blank=True, default=list)),
                ('pending_numbers', models.JSONField(blank=True, default=list)),
                ('total_spent_verified', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('removed_by', models.CharField(blank=True, default='admin-view', max_length=120)),
                ('removed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'lottery_deleted_users',
                'ordering': ['-removed_at'],
            },
        ),
    ]
