# Generated by Django 4.2.7 on 2026-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_lottery_bot_branding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cardunselectrefund',
            new_name='card_unsele_user_id_e03669_idx',
            old_name='card_unselect_refunds_user_game_idx',
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='CBE/Telebirr transaction id when manually approved (prevents reuse)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cardunselectrefund',
            name='card_number',
            field=models.PositiveIntegerField(help_text='Last unselected card (audit)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='spectator_count',
            field=models.PositiveIntegerField(default=0, help_text='Reserved for future use (not updated by gameplay currently).'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='allow_free_play_after_real_win',
            field=models.BooleanField(default=True, help_text='If True, real wins do not change free_play_allowed (first_win is still recorded). If False, every real win sets free_play_allowed=False.'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='allow_system_account',
            field=models.BooleanField(default=True, help_text='Enable fake system accounts to join games'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='card_selection_timer',
            field=models.IntegerField(default=20, help_text='Seconds for card selection window'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='default_free_play_for_new_users',
            field=models.BooleanField(default=True, help_text='If True, first-time phone registration sets user free_play_allowed=True. If False, sets False.'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='total_cards',
            field=models.IntegerField(default=100, help_text='Total number of cards available'),
        ),
        migrations.AlterField(
            model_name='lotterysettings',
            name='next_round_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Minutes to wait after winners are announced before starting a new round'),
        ),
        migrations.AddIndex(
            model_name='depositrequest',
            index=models.Index(fields=['transaction_reference'], name='deposit_req_transac_48b05b_idx'),
        ),
    ]
