"""
Django settings for bingo project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# backend/.env then repo-root/.env (EC2: /home/ubuntu/apps/CarLottery/.env)
_BACKEND_DIR = Path(__file__).resolve().parent.parent
load_dotenv(_BACKEND_DIR / '.env')
load_dotenv(_BACKEND_DIR.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = _BACKEND_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') or os.getenv('DJANGO_SECRET_KEY') or 'django-insecure-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Get allowed hosts from environment or use default
_allowed = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]

# CSRF Configuration - Required for admin panel
_csrf = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000',
)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf.split(',') if o.strip()]

# Session and CSRF Cookie settings for HTTPS
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Custom CSRF failure handler for JSON responses
CSRF_FAILURE_VIEW = 'api.csrf_handler.csrf_failure'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'channels',
    'corsheaders',
    # Local apps
    'api',
    'telegram_bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'corsheaders.middleware.CorsMiddleware',
    'api.rate_limit_middleware.RateLimitMiddleware',  # Rate limiting for promo-safe registration
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.json_error_middleware.JsonErrorMiddleware',  # Ensure API requests return JSON errors
]

ROOT_URLCONF = 'bingo.urls'

# Frontend build may live inside backend/ or at repo root (e.g. on EC2)
FRONTEND_DIST_DIRS = [
    os.path.join(BASE_DIR, 'frontend_dist'),
    os.path.join(BASE_DIR, '..', 'frontend_dist'),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [d for d in FRONTEND_DIST_DIRS if os.path.exists(d)],  # Frontend build directory (try both locations)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bingo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Database configuration for EC2 single instance
# Optimized for PostgreSQL on same EC2 instance
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'bingo_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        # Connection pooling for EC2 single instance
        'CONN_MAX_AGE': 60,  # Keep connections alive for 60 seconds (reduced for single instance)
        'OPTIONS': {
            'connect_timeout': 10,
            # Optimize for single instance PostgreSQL
            'options': '-c statement_timeout=30000',  # 30 second statement timeout
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Frontend static files (from Vite build) - use first existing location (backend/ or repo root)
FRONTEND_DIST = next((os.path.abspath(d) for d in FRONTEND_DIST_DIRS if os.path.exists(d)), os.path.join(BASE_DIR, 'frontend_dist'))
if os.path.exists(FRONTEND_DIST):
    # Add frontend_dist to static files directories
    # This includes index.html and all assets
    STATICFILES_DIRS = [
        FRONTEND_DIST,
    ]
    
    # Also add assets directory if it exists
    assets_dir = os.path.join(FRONTEND_DIST, 'assets')
    if os.path.exists(assets_dir):
        STATICFILES_DIRS.append(assets_dir)

# WhiteNoise configuration for serving static files
# Use standard storage (not manifest) since Vite already handles file hashing
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise root for serving files that aren't in STATIC_ROOT
# This allows serving index.html and other frontend files directly
WHITENOISE_ROOT = FRONTEND_DIST if os.path.exists(FRONTEND_DIST) else None

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.jwt_authentication.JWTAuthentication',  # JWT token authentication
        'rest_framework.authentication.SessionAuthentication',  # Fallback to session
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if os.getenv('CORS_ALLOWED_ORIGINS') else [
    "http://localhost:5173",  # Vue dev server
    "http://localhost:3000",
    "https://goodbingo.shop",
    "https://www.goodbingo.shop",
    "https://web.telegram.org",  # Telegram Web App
]

CORS_ALLOW_CREDENTIALS = True

# Allow all origins in development (be careful in production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Channels Configuration
ASGI_APPLICATION = 'bingo.asgi.application'

# Redis configuration for EC2 single instance
# Redis runs on same EC2 instance (localhost)
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)

# Build Redis connection URL for channels-redis
if REDIS_PASSWORD:
    REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
else:
    REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"

# Channels (WebSocket) configuration - optimized for single instance
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL],
            "capacity": 1500,  # Maximum messages per channel (optimized for ~100 concurrent users)
            "expiry": 10,  # Message expiry in seconds
        },
    },
}

# Django Cache Configuration - Use Redis for caching
# Optimized for EC2 single instance memory usage
# Note: Django's built-in Redis cache backend doesn't support MAX_ENTRIES or CULL_FREQUENCY
# Redis manages memory automatically via maxmemory policy configured in redis.conf
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'bingo_cache',
        'TIMEOUT': 300,  # Default 5 minutes timeout
        # No OPTIONS needed - Django's Redis cache backend uses minimal configuration
    }
}

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
CELERY_WORKER_PREFETCH_MULTIPLIER = 2  # Allow 2 tasks prefetched (set via command line, but keep for reference)
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion

# Queue configuration - CRITICAL for preventing gameplay starvation
# Separate queues ensure gameplay tasks are never blocked by registration/reward tasks
# Note: Task names use the format 'app_name.tasks.task_function_name'
CELERY_TASK_ROUTES = {
    # Gameplay tasks (critical, time-sensitive) -> gameplay queue
    'api.tasks.task_call_number': {'queue': 'gameplay'},
    'api.tasks.task_auto_call_numbers': {'queue': 'gameplay'},
    'api.tasks.task_check_bingo_for_all_cards': {'queue': 'gameplay'},
    'api.tasks.task_process_bingo_winners': {'queue': 'gameplay'},
    
    # NEW Redis-first gameplay tasks -> gameplay queue (CRITICAL)
    'api.tasks.task_call_next_number': {'queue': 'gameplay'},
    'api.tasks.task_mark_cards_for_number': {'queue': 'gameplay'},
    'api.tasks.task_check_bingo_for_number': {'queue': 'gameplay'},
    'api.tasks.task_finalize_game': {'queue': 'gameplay'},
    'api.tasks.task_broadcast_winner': {'queue': 'gameplay'},
    'api.tasks.task_reset_game_runtime': {'queue': 'gameplay'},
    'api.tasks.task_check_game_status_after_number': {'queue': 'gameplay'},
    
    # Registration/reward tasks (can be slower, DB-heavy) -> registration queue
    'api.tasks.task_process_registration_rewards': {'queue': 'registration'},
    
    # Other tasks -> default queue
    # (card generation, refunds, fake users, etc.)
}

# Ensure queues are created automatically
CELERY_TASK_CREATE_MISSING_QUEUES = True

# IMPORTANT: Celery worker must listen to all queues: gameplay,default,registration
# For EC2 single instance, use: celery -A bingo worker --concurrency=2 -Q gameplay,registration,default

# Default queue for tasks without explicit routing
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

# Memory optimization settings for EC2 single instance (t3.micro/t3.small)
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # Restart worker after 50 tasks to prevent memory leaks
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 150000  # Kill worker if it exceeds 150MB (reduced for t3.micro)
CELERY_TASK_IGNORE_RESULT = True  # Don't store task results to save memory
CELERY_RESULT_EXPIRES = 3600  # Expire results after 1 hour

# Worker concurrency for single instance (2-4 threads recommended for t3.micro)
# Note: This is set via command line (celery -A bingo worker --concurrency=2)
# CELERY_WORKER_CONCURRENCY = 2  # Set in systemd service file

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
# Web app URL (EC2 production or localhost for development)
TELEGRAM_WEB_APP_URL = os.getenv('TELEGRAM_WEB_APP_URL', 'https://goodbingo.shop')

# JWT Configuration
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_DELTA = 86400  # 24 hours

# Custom User Model
AUTH_USER_MODEL = 'api.User'
