"""
Django settings for bingo project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# backend/.env then repo-root/.env (EC2: /home/ubuntu/apps/DigitalLottery/.env)
_BACKEND_DIR = Path(__file__).resolve().parent.parent
load_dotenv(_BACKEND_DIR / '.env')
load_dotenv(_BACKEND_DIR.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = _BACKEND_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') or os.getenv('DJANGO_SECRET_KEY') or 'django-insecure-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Get allowed hosts from environment or use default
_allowed = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]

# CSRF Configuration - Required for admin panel
_csrf = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000',
)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf.split(',') if o.strip()]

# Session / CSRF cookies:
# Secure cookies require HTTPS. On plain HTTP (EC2 IP), Secure cookies are dropped by the browser
# which makes admin login "flash" then kick you out.
_use_https = os.getenv('USE_HTTPS', 'False').strip().lower() in ('1', 'true', 'yes')
SESSION_COOKIE_SECURE = _use_https
CSRF_COOKIE_SECURE = _use_https
SESSION_COOKIE_HTTPONLY = True
# Must be False so the Vue admin can read csrftoken from document.cookie
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Custom CSRF failure handler for JSON responses
CSRF_FAILURE_VIEW = 'api.csrf_handler.csrf_failure'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    # Local apps
    'api',
    'telegram_bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'corsheaders.middleware.CorsMiddleware',
    'api.rate_limit_middleware.RateLimitMiddleware',  # Rate limiting for promo-safe registration
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.json_error_middleware.JsonErrorMiddleware',  # Ensure API requests return JSON errors
]

ROOT_URLCONF = 'bingo.urls'

# Frontend build: Vite writes to backend/frontend_dist (see frontend/vite.config.js)
# Keep parent path as fallback for older deployments
FRONTEND_DIST_DIRS = [
    os.path.join(BASE_DIR, 'frontend_dist'),
    os.path.join(BASE_DIR, '..', 'frontend_dist'),
]

# Prefer the newest frontend_dist if both exist (avoids serving a stale copy)
def _pick_frontend_dist():
    candidates = []
    for d in FRONTEND_DIST_DIRS:
        abs_d = os.path.abspath(d)
        index = os.path.join(abs_d, 'index.html')
        if os.path.isfile(index):
            candidates.append((os.path.getmtime(index), abs_d))
    if candidates:
        candidates.sort(reverse=True)
        return candidates[0][1]
    return os.path.abspath(os.path.join(BASE_DIR, 'frontend_dist'))

FRONTEND_DIST = _pick_frontend_dist()

# Behind nginx/HTTPS terminator: build absolute media URLs as https://
if _use_https:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = False  # nginx handles redirect; avoid double-redirect loops

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [d for d in FRONTEND_DIST_DIRS if os.path.exists(d)],  # Frontend build directory (try both locations)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bingo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Database configuration for EC2 single instance
# Optimized for PostgreSQL on same EC2 instance
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'bingo_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        # Connection pooling for EC2 single instance
        'CONN_MAX_AGE': 60,  # Keep connections alive for 60 seconds (reduced for single instance)
        'OPTIONS': {
            'connect_timeout': 10,
            # Optimize for single instance PostgreSQL
            'options': '-c statement_timeout=30000',  # 30 second statement timeout
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# FRONTEND_DIST is resolved earlier via _pick_frontend_dist() (newest index.html wins)
if os.path.exists(FRONTEND_DIST):
    # Add frontend_dist to static files directories
    # This includes index.html and all assets
    STATICFILES_DIRS = [
        FRONTEND_DIST,
    ]
    
    # Also add assets directory if it exists
    assets_dir = os.path.join(FRONTEND_DIST, 'assets')
    if os.path.exists(assets_dir):
        STATICFILES_DIRS.append(assets_dir)

# WhiteNoise configuration for serving static files
# Use standard storage (not manifest) since Vite already handles file hashing
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise root for serving files that aren't in STATIC_ROOT
# This allows serving index.html and other frontend files directly
WHITENOISE_ROOT = FRONTEND_DIST if os.path.exists(FRONTEND_DIST) else None

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.jwt_authentication.JWTAuthentication',  # JWT token authentication
        'rest_framework.authentication.SessionAuthentication',  # Fallback to session
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if os.getenv('CORS_ALLOWED_ORIGINS') else [
    "http://localhost:5173",  # Vue dev server
    "http://localhost:3000",
    "https://goodbingo.shop",
    "https://www.goodbingo.shop",
    "https://web.telegram.org",  # Telegram Web App
]

CORS_ALLOW_CREDENTIALS = True

# Allow all origins in development (be careful in production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Channels Configuration
ASGI_APPLICATION = 'bingo.asgi.application'

# Redis configuration for EC2 single instance
# Redis runs on same EC2 instance (localhost)
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.getenv('REDIS_PORT', 6379))
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', None)

# Redis URL (cache + rate limiting)
if REDIS_PASSWORD:
    REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}"
else:
    REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'digitallottery_cache',
        'TIMEOUT': 300,
    }
}

# Telegram Bot Configuration
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_WEB_APP_URL = os.getenv('TELEGRAM_WEB_APP_URL', '')

# JWT Configuration
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_DELTA = 86400  # 24 hours

# Custom User Model
AUTH_USER_MODEL = 'api.User'
